# Generated by Django 5.1 on 2024-09-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_account_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
    ]
