# Generated by Django 5.1 on 2024-09-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_account_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceHistory',
            new_name='Maintenance',
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
