# Generated by Django 5.1 on 2024-09-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_maintenancehistory_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorbikemodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.company'),
        ),
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.partcategory'),
        ),
        migrations.AddField(
            model_name='part',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.company'),
        ),
    ]
