# Generated by Django 5.1 on 2024-09-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_motorbikemodel_company_part_category_part_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorbikemodel',
            old_name='name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='motorbikemodel',
            old_name='type',
            new_name='chassis_number',
        ),
        migrations.RenameField(
            model_name='motorbikemodel',
            old_name='vin',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='motorbikemodel',
            old_name='year',
            new_name='model_code',
        ),
    ]
