# Generated by Django 5.1 on 2024-09-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_rename_name_motorbikemodel_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
