# Generated by Django 5.1 on 2024-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_account_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorbikemodel',
            old_name='chassis_number',
            new_name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='motorbikemodel',
            name='engine_number',
        ),
        migrations.AddField(
            model_name='motorbikemodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motorbikemodel',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partmm',
            name='is_Maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermotorbike',
            name='chassis_number',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='usermotorbike',
            name='engine_number',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
